### ISSUE TITLE
Microsoft Authentification

### ISSUE THREAD

**Issue by Misheru504** [Ezzud/minecraftlauncher-template#1]
Is it possible to add microsoft authentification because now we cant play with a mojang account ?

**Comment by Ezzud** [comment]
done! https://github.com/Ezzud/minecraftlauncher-template/releases/tag/1.1

**Comment by kalek3** [comment]
Unfortunately I have to say that authentication with Microsoft servers does not work for me or my friends either, it recognizes the account, however it says we DO NOT own the Minecraft... I kindly ask for a way to fix this. Thank you!
